services:
  # Nuxt 网站
  website:
    build:
      context: .
      dockerfile: Dockerfile
    image: redcode-website:latest
    container_name: redcode-website
    ports:
      - "127.0.0.1:8015:8015"
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped


