version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: redcode-im/backend:latest
    container_name: redcode-backend
    restart: unless-stopped
    ports:
      - "8010:8010"
    volumes:
      - ./log:/app/log
