import path from "path";

const ROOT_DIR = path.resolve(import.meta.dir, "../../../");
const BACKEND_DIR = path.join(ROOT_DIR, "backend");
const ADMIN_DIR = path.join(ROOT_DIR, "admin");
const DASHBOARD_DIR = path.join(ROOT_DIR, "dashboard");
const WEBSITE_DIR = path.join(ROOT_DIR, "website");
const FRONTEND_DIR = path.join(ROOT_DIR, "frontend");
const DESKTOP_DIR = path.join(ROOT_DIR, "desktop");
const TESTS_DIR = path.join(ROOT_DIR, "tests");
const TESTS_GO_DIR = path.join(TESTS_DIR, "go");

export type CommandGroup = "env" | "dev" | "test" | "deploy";
export type CommandSection = string;
export type CommandType = "oneshot" | "daemon";

export interface Command {
  name: string;
  description: string;
  group: CommandGroup;
  section: CommandSection;
  type: CommandType;
  cmd: string[];
  cwd: string;
  env?: Record<string, string>;
}

export const commands = {
  // ========== 开发环境 ==========
  "docker:up": {
    name: "启动 Docker 服务",
    description: "启动 PostgreSQL + Redis 开发环境",
    group: "env",
    section: "Docker 服务",
    type: "oneshot",
    cmd: [
      "docker-compose",
      "-f",
      "docker/docker-compose.dev.yml",
      "up",
      "-d",
      "postgres",
      "redis-session",
      "redis-cache",
    ],
    cwd: BACKEND_DIR,
  },
  "docker:restart": {
    name: "重启 Docker 服务",
    description: "重启 PostgreSQL + Redis",
    group: "env",
    section: "Docker 服务",
    type: "oneshot",
    cmd: ["docker-compose", "-f", "docker/docker-compose.dev.yml", "restart"],
    cwd: BACKEND_DIR,
  },
  "docker:logs": {
    name: "查看 Docker 日志",
    description: "查看容器日志（最近 100 行）",
    group: "env",
    section: "Docker 服务",
    type: "daemon",
    cmd: [
      "docker-compose",
      "-f",
      "docker/docker-compose.dev.yml",
      "logs",
      "--tail=100",
      "-f",
    ],
    cwd: BACKEND_DIR,
  },
  "docker:down": {
    name: "停止 Docker 服务",
    description: "停止所有 Docker 容器",
    group: "env",
    section: "Docker 服务",
    type: "oneshot",
    cmd: ["docker-compose", "-f", "docker/docker-compose.dev.yml", "down", "--remove-orphans"],
    cwd: BACKEND_DIR,
  },
  "redis-commander": {
    name: "Redis 可视化",
    description: "启动 Redis Commander (8081)",
    group: "env",
    section: "Docker 服务",
    type: "oneshot",
    cmd: [
      "docker-compose",
      "-f",
      "docker/docker-compose.dev.yml",
      "--profile",
      "tools",
      "up",
      "-d",
      "redis-commander",
    ],
    cwd: BACKEND_DIR,
  },
  "db:migrate": {
    name: "数据库迁移",
    description: "启动后端自动执行迁移",
    group: "env",
    section: "数据库操作",
    type: "oneshot",
    cmd: ["cargo", "run", "--", "--migrate-only"],
    cwd: BACKEND_DIR,
  },
  "db:verify": {
    name: "验证迁移",
    description: "验证 base.sql 完整性",
    group: "env",
    section: "数据库操作",
    type: "oneshot",
    cmd: ["bash", "scripts/verify-base-sql.sh"],
    cwd: BACKEND_DIR,
  },
  "db:clear": {
    name: "清空数据",
    description: "清空业务数据（保留表结构）",
    group: "env",
    section: "数据库操作",
    type: "oneshot",
    cmd: ["bash", "scripts/clear-database.sh"],
    cwd: BACKEND_DIR,
  },
  "db:reset": {
    name: "重建数据库",
    description: "删除所有数据并重建（含卷数据）",
    group: "env",
    section: "数据库操作",
    type: "oneshot",
    cmd: ["docker-compose", "-f", "docker/docker-compose.dev.yml", "down", "-v"],
    cwd: BACKEND_DIR,
  },

  // ========== 开发模块 ==========
  "backend:run": {
    name: "启动后端服务",
    description: "cargo run 启动 Rust 后端",
    group: "dev",
    section: "Backend",
    type: "daemon",
    cmd: ["cargo", "run"],
    cwd: BACKEND_DIR,
    env: { RUST_LOG: "info" },
  },
  "backend:watch": {
    name: "后端热重载",
    description: "cargo watch 监听文件变化自动重启",
    group: "dev",
    section: "Backend",
    type: "daemon",
    cmd: ["cargo", "watch", "-x", "run"],
    cwd: BACKEND_DIR,
    env: { RUST_LOG: "info" },
  },
  "admin:dev": {
    name: "启动 Admin 前端",
    description: "Vite Dev Server（admin）",
    group: "dev",
    section: "Admin 后台",
    type: "daemon",
    cmd: ["bun", "run", "dev"],
    cwd: ADMIN_DIR,
  },
  "dashboard:dev": {
    name: "启动 Dashboard",
    description: "Bun + Hono Dashboard（20000）",
    group: "dev",
    section: "Dashboard",
    type: "daemon",
    cmd: ["bun", "run", "dev"],
    cwd: DASHBOARD_DIR,
  },
  "website:dev": {
    name: "启动 Website",
    description: "Nuxt Dev Server（website）",
    group: "dev",
    section: "网站",
    type: "daemon",
    cmd: ["bun", "run", "dev"],
    cwd: WEBSITE_DIR,
  },
  "frontend:dev": {
    name: "启动 Flutter（dev）",
    description: "frontend/scripts/run_dev.sh",
    group: "dev",
    section: "移动端",
    type: "daemon",
    cmd: ["bash", "scripts/run_dev.sh"],
    cwd: FRONTEND_DIR,
  },

  // ========== 测试 ==========
  "test:go": {
    name: "Go API 测试",
    description: "Go 黑盒测试",
    group: "test",
    section: "测试执行",
    type: "oneshot",
    cmd: ["go", "test", "./...", "-v"],
    cwd: TESTS_GO_DIR,
    env: { API_BASE_URL: "http://localhost:8010" },
  },
  "test:unit": {
    name: "Rust 单元测试",
    description: "cargo test --lib",
    group: "test",
    section: "测试执行",
    type: "oneshot",
    cmd: ["cargo", "test", "--lib"],
    cwd: BACKEND_DIR,
  },
  "test:integration": {
    name: "Rust 集成测试",
    description: "cargo test --tests",
    group: "test",
    section: "测试执行",
    type: "oneshot",
    cmd: ["cargo", "test", "--tests", "--", "--test-threads=1"],
    cwd: BACKEND_DIR,
  },
  "test:all": {
    name: "一键回归",
    description: "完整测试套件（Docker）",
    group: "test",
    section: "测试执行",
    type: "oneshot",
    cmd: ["bash", "run.sh"],
    cwd: TESTS_DIR,
  },
  "test:flow": {
    name: "API 流程测试",
    description: "准备测试数据",
    group: "test",
    section: "测试执行",
    type: "oneshot",
    cmd: ["bash", "test_flow.sh"],
    cwd: BACKEND_DIR,
  },
  "test:admin:e2e": {
    name: "Admin E2E 测试",
    description: "Playwright Test Runner",
    group: "test",
    section: "测试执行",
    type: "oneshot",
    cmd: ["bun", "run", "test:e2e"],
    cwd: ADMIN_DIR,
  },
  "coverage:update": {
    name: "更新 API 覆盖率",
    description: "扫描测试代码，更新 API 覆盖率 JSON",
    group: "test",
    section: "覆盖率",
    type: "oneshot",
    cmd: ["go", "run", "./cmd/route_coverage"],
    cwd: TESTS_GO_DIR,
  },
  "coverage:json": {
    name: "更新代码覆盖率",
    description: "生成测试覆盖率 JSON 数据（Rust 行覆盖率 + 测试统计）",
    group: "test",
    section: "覆盖率",
    type: "oneshot",
    cmd: ["bash", "update-coverage-json.sh"],
    cwd: TESTS_DIR,
  },
  "test:coverage": {
    name: "生成覆盖率报告",
    description: "生成 HTML 覆盖率报告",
    group: "test",
    section: "覆盖率",
    type: "oneshot",
    cmd: ["bash", "coverage.sh"],
    cwd: TESTS_DIR,
  },
  "check": {
    name: "编译检查",
    description: "cargo check",
    group: "test",
    section: "质量检查",
    type: "oneshot",
    cmd: ["cargo", "check"],
    cwd: BACKEND_DIR,
  },
  "clippy": {
    name: "Clippy 检查",
    description: "代码质量检查",
    group: "test",
    section: "质量检查",
    type: "oneshot",
    cmd: ["cargo", "clippy"],
    cwd: BACKEND_DIR,
  },
  "fmt": {
    name: "代码格式化",
    description: "cargo fmt",
    group: "test",
    section: "质量检查",
    type: "oneshot",
    cmd: ["cargo", "fmt"],
    cwd: BACKEND_DIR,
  },
  "fmt:check": {
    name: "格式检查",
    description: "cargo fmt --check",
    group: "test",
    section: "质量检查",
    type: "oneshot",
    cmd: ["cargo", "fmt", "--", "--check"],
    cwd: BACKEND_DIR,
  },

  // ========== 部署 ==========
  "build:debug": {
    name: "Debug 构建",
    description: "cargo build",
    group: "deploy",
    section: "服务端构建",
    type: "oneshot",
    cmd: ["cargo", "build"],
    cwd: BACKEND_DIR,
  },
  "build:release": {
    name: "Release 构建",
    description: "cargo build --release",
    group: "deploy",
    section: "服务端构建",
    type: "oneshot",
    cmd: ["cargo", "build", "--release"],
    cwd: BACKEND_DIR,
  },
  "build:linux": {
    name: "Linux 交叉编译",
    description: "使用 Zig 编译 Linux 版本",
    group: "deploy",
    section: "服务端构建",
    type: "oneshot",
    cmd: ["bash", "scripts/build-linux-zig.sh"],
    cwd: BACKEND_DIR,
  },
  "deploy:backend": {
    name: "部署 Backend",
    description: "构建并上传后端到服务器",
    group: "deploy",
    section: "服务端部署",
    type: "oneshot",
    cmd: ["bash", "deploy.sh"],
    cwd: BACKEND_DIR,
  },
  "deploy:admin": {
    name: "部署 Admin",
    description: "构建并上传后台",
    group: "deploy",
    section: "后台部署",
    type: "oneshot",
    cmd: ["bash", "deploy.sh"],
    cwd: ADMIN_DIR,
  },
  "deploy:website": {
    name: "部署 Website",
    description: "构建并上传官网",
    group: "deploy",
    section: "网站部署",
    type: "oneshot",
    cmd: ["bash", "deploy.sh"],
    cwd: WEBSITE_DIR,
  },
  "website:build": {
    name: "Website 构建包",
    description: "website/build.sh",
    group: "deploy",
    section: "网站构建",
    type: "oneshot",
    cmd: ["bash", "build.sh"],
    cwd: WEBSITE_DIR,
  },
  "desktop:build:macos": {
    name: "Desktop macOS 构建",
    description: "desktop/scripts/build-macos.sh",
    group: "deploy",
    section: "桌面端构建",
    type: "oneshot",
    cmd: ["bash", "scripts/build-macos.sh"],
    cwd: DESKTOP_DIR,
  },
  "desktop:build:windows": {
    name: "Desktop Windows 构建",
    description: "desktop/scripts/build-windows.sh",
    group: "deploy",
    section: "桌面端构建",
    type: "oneshot",
    cmd: ["bash", "scripts/build-windows.sh"],
    cwd: DESKTOP_DIR,
  },
  "desktop:build:linux": {
    name: "Desktop Linux 构建",
    description: "desktop/scripts/build-linux.sh",
    group: "deploy",
    section: "桌面端构建",
    type: "oneshot",
    cmd: ["bash", "scripts/build-linux.sh"],
    cwd: DESKTOP_DIR,
  },
  "desktop:build:updater": {
    name: "Desktop Updater 构建",
    description: "desktop/scripts/build-updater.sh",
    group: "deploy",
    section: "桌面端构建",
    type: "oneshot",
    cmd: ["bash", "scripts/build-updater.sh"],
    cwd: DESKTOP_DIR,
  },
  "frontend:build": {
    name: "Flutter 构建",
    description: "frontend/scripts/build.sh",
    group: "deploy",
    section: "移动端构建",
    type: "oneshot",
    cmd: ["bash", "scripts/build.sh"],
    cwd: FRONTEND_DIR,
  },
  "frontend:build:android": {
    name: "Android 包",
    description: "frontend/scripts/build_android.sh",
    group: "deploy",
    section: "移动端构建",
    type: "oneshot",
    cmd: ["bash", "scripts/build_android.sh"],
    cwd: FRONTEND_DIR,
  },
  "frontend:build:ipa": {
    name: "iOS IPA",
    description: "frontend/scripts/build_ipa.sh",
    group: "deploy",
    section: "移动端构建",
    type: "oneshot",
    cmd: ["bash", "scripts/build_ipa.sh"],
    cwd: FRONTEND_DIR,
  },
  "frontend:build:android-hot-patch": {
    name: "Android 热更新包",
    description: "frontend/scripts/build_android_hot_patch.sh",
    group: "deploy",
    section: "移动端构建",
    type: "oneshot",
    cmd: ["bash", "scripts/build_android_hot_patch.sh"],
    cwd: FRONTEND_DIR,
  },
  "frontend:build:ios-hot-patch": {
    name: "iOS 热更新包",
    description: "frontend/scripts/build_ios_hot_patch.sh",
    group: "deploy",
    section: "移动端构建",
    type: "oneshot",
    cmd: ["bash", "scripts/build_ios_hot_patch.sh"],
    cwd: FRONTEND_DIR,
  },
} as const satisfies Record<string, Command>;

export type CommandId = keyof typeof commands;
